# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-06 08:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='schedule_data',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
