# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-05-03 04:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_user_schedule_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='schedule_data',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
