# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-05-06 02:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_user_timetableurl'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teamcode', models.CharField(max_length=20)),
                ('member_kakao_id', models.TextField(null=True)),
                ('schedule_data', models.TextField(null=True)),
                ('alarm_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
