# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-05-14 14:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0005_teamschedule'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TeamSchedule',
        ),
    ]
