# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-05-15 04:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0006_delete_teamschedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teamcode', models.CharField(max_length=20)),
                ('alarm_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('kakao_id_list', models.TextField(null=True)),
                ('schedule_data', models.CharField(max_length=200, null=True)),
                ('timetableurl', models.TextField(null=True)),
            ],
        ),
    ]
