# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-05-19 03:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0007_teaminfo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teaminfo',
            old_name='timetableurl',
            new_name='timetablehtml',
        ),
    ]
