# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-05-19 05:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0008_auto_20180519_1224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teaminfo',
            name='alarm_date',
        ),
        migrations.AddField(
            model_name='teaminfo',
            name='alarm_data',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='teaminfo',
            name='alarm_data_before_time',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
