# Generated by Django 2.0.4 on 2018-06-12 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0010_user_alarm_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='alarm_send_flag',
            field=models.BooleanField(default=False),
        ),
    ]
