# Generated by Django 2.0.4 on 2018-05-06 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsed_data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyroomdata',
            name='offTime',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='studyroomdata',
            name='floor',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='studyroomdata',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
